services:
    client:
        build: .
        container_name: reactjs-vite
        ports:
            - "3333:3000"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
